# Generated by Django 3.0.2 on 2020-05-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200508_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogKeywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='文章关键词')),
                ('is_abort', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文章关键词',
                'verbose_name_plural': '文章关键词',
            },
        ),
        migrations.AddField(
            model_name='blogarticle',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='blogs.BlogKeywords', verbose_name='关键词'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='blogs.BlogKeywords', verbose_name='关键词'),
        ),
    ]
