# Generated by Django 3.0.2 on 2020-05-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20200508_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogarticle',
            name='slug',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='slug',
            field=models.CharField(max_length=200, null=True, verbose_name=''),
        ),
    ]
