# Generated by Django 3.0.2 on 2020-05-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_auto_20200509_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogarticle',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='拼音slug'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='slug',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='拼音slug'),
        ),
    ]
